title: Proyectos de Programación Orientada a Objetos
description: Área de Computación e Informática, UASLP
google_analytics: 
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
